name: CHASMplus
channels:
- bioconda
- defaults
- r
dependencies:
- r
- r-essentials
- r-randomforest
- r-getopt
- python
- setuptools
- pip
- pysam
- rpy2
- snakemake
- matplotlib
- numpy
- scipy
- pandas
- scikit-learn
- pyyaml
- pip:
  - probabilistic2020==1.2.0
